login_check:
    pattern:   /project-management/access/login_check
      
overlord_frontend:
    resource: "@OverlordFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

overlord_admin:
    resource: "@OverlordAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

overlord_project:
    resource: "@OverlordProjectBundle/Controller/"
    type:     annotation
    prefix:   /project-management

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
