jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    providers:
        main:
            entity: { class: Overlord\Bundle\CoreBundle\Entity\User, property: email }
            
    encoders:
        Overlord\Bundle\CoreBundle\Entity\Admin:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/project-management/access/login$
            security: false

        secured_area:
            pattern:    ^/project-management/
            form_login:
                check_path: login_check
                login_path: login
            logout:
                path:   /project-management/access/logout
                target: /project-management/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
